version: '3'
services:
  keycloak:
    image: 982306614752.dkr.ecr.us-west-2.amazonaws.com/keycloak:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      PROXY_ADDRESS_FORWARDING: ${PROXY_ADDRESS_FORWARDING}
    ports:
      - 8080:8080
      - 8443:8443