apiVersion: builtin
kind: LabelTransformer
metadata:
  name: global-labels
labels:
  com.bhn.service: keycloak
fieldSpecs:
- path: metadata/labels
  create: true
- path: spec/template/metadata/labels
  create: true