apiVersion: v1
kind: Namespace
metadata:
  name: iam
---
apiVersion: v1
kind: Service
metadata:
  labels:
    com.bhn.service: keycloak
  name: keycloak
  namespace: iam
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8443"
      port: 8443
      targetPort: 8443
  selector:
    com.bhn.service: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    com.bhn.service: keycloak
  name: keycloak
  namespace: iam
spec:
  replicas: 1
  selector:
    matchLabels:
      com.bhn.service: keycloak
  strategy: {}
  template:
    metadata:
      labels:
        com.bhn.service: keycloak
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: ${DATABASE_URL}
            - name: KEYCLOAK_PASSWORD
              value: ${KEYCLOAK_PASSWORD}
            - name: KEYCLOAK_USER
              value: ${KEYCLOAK_USER}
            - name: PROXY_ADDRESS_FORWARDING
              value: "${PROXY_ADDRESS_FORWARDING}"
          image: 982306614752.dkr.ecr.us-west-2.amazonaws.com/keycloak:latest
          name: keycloak
          ports:
            - containerPort: 8080
            - containerPort: 8443
          resources: {}
      restartPolicy: Always
status: {}
