---
kind: Service
apiVersion: v1
metadata:
  name: keycloak-metrics
  labels:
    com.bhn.service: keycloak
    component: metrics
spec:
  selector:
    com.bhn.service: keycloak
  ports:
    - name: metrics
      port: 9990
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak
  labels:
    k8s-app: keycloak
    com.bhn.service: keycloak
spec:
  endpoints:
    - interval: 10s
      port: metrics
      scheme: http
      path: /metrics
  jobLabel: k8s-app
  selector:
    matchLabels:
      app: keycloak
      component: metrics